### ISSUE TITLE
How can i say which server to connect to?

### ISSUE THREAD

**Issue by FWSimon** [geminilabs/elixir-rsync#1]
Hey, nice plugin, but how can i say which server to connect to?

**Comment by pryley** [comment]
This Elixir plugin was made to sync a local dir to another local dir.

You can try to set the destination to the server url and set any args, but I haven't tested this.

```
mx.rsync( {path to source}, {server url for destination}, {additional rsync args} );
```

You may want to create your own custom gulp task to perform remote rsync.
